ui <- shinyUI(fluidPage(
  headerPanel('NEON data aggregation by species'),
  sidebarPanel(
    selectInput('group','data type',c('smallMammal','carabid','mosquito',
                                      'pathogen','plantPresenceCover')),
    selectInput('space.Agg','spatial scale',c('byDomain','bySite','byPlot')),
    selectInput('time.Agg','temporal scale',c("aggAll",'byYear','byMonthYear','byBout')),
    selectInput('typeFiles','file type for plant presence',c("none",'1m2Data','10m2Data','100m2Data','400m2Data')),
    numericInput('numcols', label = "number of columns to display",value=4),
    h3("Download data"),
    downloadButton('downloadData', 'Download')
    ),
  
  mainPanel(
    tabsetPanel(
      tabPanel('help',
               em(helpText("This code will help you extract data from the NEON project for four different 
                            taxa (small mammals, carabids, mosquitoes, plant cover) and for pathogen presence 
                            in mosquitoes.  These data can then be aggregated using different choices of 
                           spatial and temporal resolution.")),
               helpText(strong('data type:'), "Choose the taxa for which you want data."),
               helpText(strong('spatial scale:'), "Choice of spatial aggregation scale."),
               helpText(strong('temporal scale:'), "Choice of temporal aggregation scale."),
               helpText(strong('file type for plant presence:'), "If data type = 'plantPresenceCover' choose the scale at which the data was collected 
                        among 1m2, 10m2, 100m2 or 400m2."),
               helpText(strong('number of columns to display:'), "Given that the NEON files contain information on several hundred 
                        species, this choice is only used for immediate visualization purposes.  It determines the number of columns 
                        that are shown in the 'preview data' tab.  If a large number of columns is selected you will need to scroll to 
                        the right to see some of them."),
               helpText(strong('Download data:'), "Press this button to generate and download to your computer 
                        a copy of the dataset generated by the code.")),
      tabPanel('preview data',
               dataTableOutput("aggData")),
      tabPanel('summary',
               dataTableOutput("summary"))
      )
    )
  
))

source("server.R")
shinyApp(ui = ui, server = serverAgg)